# Example Render configuration. You will need to adjust this for the different services you run.
services:
  - type: web
    name: rails
    plan: free
    runtime: ruby
    region: oregon # the region must be consistent across all services for the internal keys to be read
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    healthCheckPath: "/up"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: SOLID_QUEUE_IN_PUMA
        value: true
      - key: DATABASE_URL
        fromDatabase:
          name: primary
          property: connectionString
      - key: CABLE_DATABASE_URL
        fromDatabase:
          name: solid_cable
          property: connectionString
      - key: CACHE_DATABASE_URL
        fromDatabase:
          name: solid_cache
          property: connectionString
      - key: QUEUE_DATABASE_URL
        fromDatabase:
          name: solid_queue
          property: connectionString
      # Uncomment the following config if you want to use Redis
      # - key: REDIS_URL
      #   fromService:
      #     type: redis
      #     name: redis
      #     property: connectionString

  # Uncomment the following blueprint if you want to use Redis
  # - type: redis
  #   name: redis
  #   region: oregon # the region must be consistent across all services for the internal keys to be read
  #   ipAllowList: [] # only allow internal connections
  #   plan: free # optional (defaults to starter)
  #   maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  # Uncomment the following blueprint if you want to enable a Sidekiq worker
  # - type: worker
  #   name: sidekiq-worker
  #   env: ruby
  #   plan: starter # no free option for bg workers
  #   region: oregon # the region must be consistent across all services for the internal keys to be read
  #   buildCommand: "./bin/render-build.sh --skip-migrate"
  #   startCommand: bundle exec sidekiq -e production
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: postgres
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         name: redis
  #         type: redis
  #         property: connectionString
  #     - key: RAILS_MASTER_KEY
  #       sync: false

# Render's "free" databases are deleted after 30 days unless upgraded and only one per workspace. Instead, default to the smallest paid size.
databases:
  - name: primary
    plan: basic-256mb
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections

  - name: solid_cable
    plan: basic-256mb
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections

  - name: solid_cache
    plan: basic-256mb
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections

  - name: solid_queue
    plan: basic-256mb
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections
