# Example Render configuration. You will need to adjust this for the different services you run.
services:
  - type: web
    name: rails
    plan: free
    runtime: ruby
    region: oregon # the region must be consistent across all services for the internal keys to be read
    buildCommand: "./bin/render-build.sh"
    startCommand: bundle exec rails s
    healthCheckPath: "/up"
    envVars:
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
      - key: DATABASE_URL
        fromDatabase:
          name: postgres
          property: connectionString
      # Uncomment the following config if you want to use Redis
      # - key: REDIS_URL
      #   fromService:
      #     type: redis
      #     name: redis
      #     property: connectionString

  # Uncomment the following blueprint if you want to use Redis
  # - type: redis
  #   name: redis
  #   region: oregon # the region must be consistent across all services for the internal keys to be read
  #   ipAllowList: [] # only allow internal connections
  #   plan: free # optional (defaults to starter)
  #   maxmemoryPolicy: noeviction # optional (defaults to allkeys-lru)

  # Uncomment the following blueprint if you want to enable a background worker
  # - type: worker
  #   name: sidekiq-worker
  #   env: ruby
  #   plan: starter # no free option for bg workers
  #   region: oregon # the region must be consistent across all services for the internal keys to be read
  #   buildCommand: "./bin/render-build-worker.sh --skip-migrate"
  #   startCommand: bundle exec sidekiq -e production
  #   envVars:
  #     - key: DATABASE_URL
  #       fromDatabase:
  #         name: postgres
  #         property: connectionString
  #     - key: REDIS_URL
  #       fromService:
  #         name: redis
  #         type: redis
  #         property: connectionString
  #     - key: RAILS_MASTER_KEY
  #       sync: false

databases:
  - name: postgres
    plan: free
    region: oregon # the region must be consistent across all services for the internal keys to be read
    ipAllowList: [] # only allow internal connections
