---
application_name: WYN
business_name: DYB, L.L.C.
business_address: 
domain: 
support_email: support@example.com
default_from_email: My App <no-reply@example.com>
background_job_processor: 
email_provider: 
account_types: both
apns: false
fcm: false
integrations:
omniauth_providers:
payment_processors:
multitenancy:
gems:
